export const SET_BUDGET = "SET_BUDGET";
export const ADD_BUDGET_GROUP = "ADD_BUDGET_GROUP";
export const REMOVE_BUDGET_GROUP = "REMOVE_BUDGET_GROUP";
export const CHANGE_BUDGET_NAME = "CHANGE_BUDGET_NAME";